# Sort Tests

Cells with implementations of various sorting and path finding algorithms.

### Auxiliary Algorithms

In [5]:
import numpy as np

For quicksort.

In [1]:
def swap(data, i, j):
    data[i], data[j] = data[j], data[i]

In [36]:
def partition(data, i, j):
    pivot = data[j]
    left, right = i, j - 1
    
    while left < right:
        while data[left] < pivot and left < right:
            left += 1
        
        while data[right] > pivot and left < right:
            right -= 1
        
        if data[left] > data[right]:
            swap(data, left, right)
            left += 1
            right -= 1

    swap(data, left, j)
    return left

### Quicksort

In [37]:
def quicksort(data, i, j):
    
    if i < j:
        index = partition(data, i, j)
        print(data)
        quicksort(data, i, index - 1)
        quicksort(data, index + 1, j)

Test quicksort.

In [39]:
data = np.random.randint(0, 20, size=10)
print(f'data before {data}')
quicksort(data, 0, len(data) - 1)
print(f'data after {data}')

data before [11  6  9 13  9 16  4 14  6  0]
[ 0  6  9 13  9 16  4 14  6 11]
[ 0  6  9  6  9  4 11 14 13 16]
[ 0  4  9  6  9  6 11 14 13 16]
[ 0  4  6  6  9  9 11 14 13 16]
[ 0  4  6  6  9  9 11 14 13 16]
[ 0  4  6  6  9  9 11 14 16 13]
data after [ 0  4  6  6  9  9 11 14 16 13]
