# Algorithms Develompent Space

  1. Quicksort
  1. Memoization

# Quick Sort Test

In [1]:
import numpy as np

Define quicksort algorithm.

First generate data to sort.

In [ ]:
def xswap(array)

In [616]:
array = [1,2,3, 5, 4, 3]
xswap(array, 1, 4)
array

[1, 4, 3, 5, 2, 3]

In [453]:
data = np.random.randint(0, 10, size=5)
data

array([4, 5, 3, 8, 0])

Define `swap` function.

In [491]:
# Function to "swap" two numbers (i.e., move a number to the right while preserving order of previous integers)
def swap(data, i, j):
    ''' 
    Move an element at index i after index j and move any numbers inbetween to the left
    
    Parameters
    ----------
        data (list, np.array) : Array with numbers to swap
        i (int) : Index of first number to swap
        j (int) : Index of second number to swap
    '''
    if data is not None:
        data[i], data[j] = data[j], data[i]

Test `swap` function.

In [495]:
swap(data, 1, 4)
data

array([4, 0, 8, 3, 5])

Define `partition` function.

In [605]:
# Function to partition an array according to a pivot point. Default is rightmost pivot.
def partition(data, i, j):
    pivot = data[j]
    left, right = i, j - 1
    
    while left <= right:
        print(f"data {data}, data[left] {data[left]}, data[right] {data[right]}, pivot {pivot}, left {left}, right {right}")
        while data[left] < pivot and left < len(data):
            print(f'data[left] {data[left]}')
            left += 1
        
        while data[right] > pivot and right > left:
            print(f'data[right] {data[right]}')
            right -= 1
            
        print(f'Post two whiles left {left} and right {right}. Data left {data[left]} and data right {data[right]}')
        
        if data[left] >= pivot:
            print('swapping')
            swap(data, left, right)
            left += 1
            right -= 1
#         print(left, right)
    swap(data, left, j)
    return left

In [608]:
data = np.random.randint(0, 10, size=10)
data

array([4, 5, 2, 6, 8, 2, 2, 9, 5, 6])

In [609]:
print(partition(data, 0, len(data) - 1))
data

data [4 5 2 6 8 2 2 9 5 6], data[left] 4, data[right] 5, pivot 6, left 0, right 8
data[left] 4
data[left] 5
data[left] 2
Post two whiles left 3 and right 8. Data left 6 and data right 5
swapping
data [4 5 2 5 8 2 2 9 6 6], data[left] 8, data[right] 9, pivot 6, left 4, right 7
data[right] 9
Post two whiles left 4 and right 6. Data left 8 and data right 2
swapping
data [4 5 2 5 2 2 8 9 6 6], data[left] 2, data[right] 2, pivot 6, left 5, right 5
data[left] 2
Post two whiles left 6 and right 5. Data left 8 and data right 2
swapping
7


array([4, 5, 2, 5, 2, 8, 2, 6, 6, 9])

In [522]:
swap(data, 3, 4)
data

array([3, 0, 4, 5, 8])

Test partition function.

In [435]:
data = np.random.randint(0, 10, size=10)
data

array([9, 1, 9, 5, 1, 7, 9, 1, 0, 1])

# Memoization

In [2]:
import numpy as np

In [38]:
memo = {}

In [39]:
def fib(n):
    if n in memo:
        return memo[n]
    elif n <= 1:
        memo[n] = 1
        return memo[n]
    else:
        x = fib(n - 1) + fib(n - 2)
        memo[n] = x
        return memo[n]

In [42]:
fib(2000)

6835702259575806647045396549170580107055408029365524565407553367798082454408054014954534318953113802726603726769523447478238192192714526677939943338306101405105414819705664090901813637296453767095528104868264704914433529355579148731044685634135487735897954629842516947101494253575869699893400976539545740214819819151952085089538422954565146720383752121972115725761141759114990448978941370030912401573418221496592822626