# Quick Sort Test

In [1]:
import numpy as np

Define quicksort algorithm.

First generate data to sort.

In [ ]:
def xswap(array)

In [616]:
array = [1,2,3, 5, 4, 3]
xswap(array, 1, 4)
array

[1, 4, 3, 5, 2, 3]

In [453]:
data = np.random.randint(0, 10, size=5)
data

array([4, 5, 3, 8, 0])

Define `swap` function.

In [437]:
# # Function to "swap" two numbers (i.e., move a number to the right while preserving order of previous integers)
# def swap(data, i, j):
#     ''' 
#     Move an element at index i after index j and move any numbers inbetween to the left
    
#     Parameters
#     ----------
#         data (list, np.array) : Array with numbers to swap
#         i (int) : Index of first number to swap
#         j (int) : Index of second number to swap
#     '''
#     if len(data) < j:
#         return None
    
#     gap = abs(j - i)
#     base = min([i, j])
    
#     print(f'In `swap`: i={i}, j={j}')
#     while gap > 0:
#         k = base + gap
#         data[i], data[k] = data[k], data[i]
#         gap -= 1

In [491]:
# Function to "swap" two numbers (i.e., move a number to the right while preserving order of previous integers)
def swap(data, i, j):
    ''' 
    Move an element at index i after index j and move any numbers inbetween to the left
    
    Parameters
    ----------
        data (list, np.array) : Array with numbers to swap
        i (int) : Index of first number to swap
        j (int) : Index of second number to swap
    '''
    if data is not None:
        data[i], data[j] = data[j], data[i]

Test `swap` function.

In [495]:
swap(data, 1, 4)
data

array([4, 0, 8, 3, 5])

Define `partition` function.

In [447]:
# # Function to partition an array according to a pivot point. Default is rightmost pivot.
# def partition(data, i, j):
#     swaps = 0
#     pivot_k = j
#     pivot = data[j]
#     for k, item in enumerate(data):
#         print(f'Current data {data}\nPivot={pivot}\tItem={item}')
#         print(f'Current index {k}\tPivot index {pivot_k}')

#         # if the item is greater than the pivot (value) and the item is left of the pivot
#         if item >= pivot and pivot_k > k:
#             swap(data, k + swaps, pivot_k)
#             pivot_k -= 1
#             swaps += 1

#         # If the item is less than the pivot (value) and to the left of the pivot
#         if item < pivot and pivot_k < k:
#             swap(data, j, k)
#             pivot_k = k
# #             swaps += 1

# #             print(f'In `partition`: item={item} pivot={pivot} i={i} j={j} data={data}')
# #             print(f'Post swap : data={data}')
# #             counter += 1
# #             j -= 1
#         print(f'Post swap data {data}')
#     return swaps

In [605]:
# Function to partition an array according to a pivot point. Default is rightmost pivot.
def partition(data, i, j):
    pivot = data[j]
    left, right = i, j - 1
    
    while left <= right:
        print(f"data {data}, data[left] {data[left]}, data[right] {data[right]}, pivot {pivot}, left {left}, right {right}")
        while data[left] < pivot and left < len(data):
            print(f'data[left] {data[left]}')
            left += 1
        
        while data[right] > pivot and right > left:
            print(f'data[right] {data[right]}')
            right -= 1
            
        print(f'Post two whiles left {left} and right {right}. Data left {data[left]} and data right {data[right]}')
        
        if data[left] >= pivot:
            print('swapping')
            swap(data, left, right)
            left += 1
            right -= 1
#         print(left, right)
    swap(data, left, j)
    return left

In [608]:
data = np.random.randint(0, 10, size=10)
data

array([4, 5, 2, 6, 8, 2, 2, 9, 5, 6])

In [609]:
print(partition(data, 0, len(data) - 1))
data

data [4 5 2 6 8 2 2 9 5 6], data[left] 4, data[right] 5, pivot 6, left 0, right 8
data[left] 4
data[left] 5
data[left] 2
Post two whiles left 3 and right 8. Data left 6 and data right 5
swapping
data [4 5 2 5 8 2 2 9 6 6], data[left] 8, data[right] 9, pivot 6, left 4, right 7
data[right] 9
Post two whiles left 4 and right 6. Data left 8 and data right 2
swapping
data [4 5 2 5 2 2 8 9 6 6], data[left] 2, data[right] 2, pivot 6, left 5, right 5
data[left] 2
Post two whiles left 6 and right 5. Data left 8 and data right 2
swapping
7


array([4, 5, 2, 5, 2, 8, 2, 6, 6, 9])

In [522]:
swap(data, 3, 4)
data

array([3, 0, 4, 5, 8])

Test partition function.

In [435]:
data = np.random.randint(0, 10, size=10)
data

array([9, 1, 9, 5, 1, 7, 9, 1, 0, 1])

In [436]:
partition(data, 0, data.size - 1)
data

Current data [9 1 9 5 1 7 9 1 0 1]
Pivot=1	Item=9
Current index 0	Pivot index 9
In `swap`: i=0, j=9
Post swap data [1 9 5 1 7 9 1 0 1 9]
Current data [1 9 5 1 7 9 1 0 1 9]
Pivot=1	Item=9
Current index 1	Pivot index 8
In `swap`: i=2, j=8
Post swap data [1 9 1 7 9 1 0 1 5 9]
Current data [1 9 1 7 9 1 0 1 5 9]
Pivot=1	Item=1
Current index 2	Pivot index 7
In `swap`: i=4, j=7
Post swap data [1 9 1 7 1 0 1 9 5 9]
Current data [1 9 1 7 1 0 1 9 5 9]
Pivot=1	Item=7
Current index 3	Pivot index 6
In `swap`: i=6, j=6
Post swap data [1 9 1 7 1 0 1 9 5 9]
Current data [1 9 1 7 1 0 1 9 5 9]
Pivot=1	Item=1
Current index 4	Pivot index 5
In `swap`: i=8, j=5
Post swap data [1 9 1 7 1 0 9 5 1 9]
Current data [1 9 1 7 1 0 9 5 1 9]
Pivot=1	Item=0
Current index 5	Pivot index 4
In `swap`: i=9, j=5
Post swap data [1 9 1 7 1 0 5 1 9 9]
Current data [1 9 1 7 1 0 5 1 9 9]
Pivot=1	Item=5
Current index 6	Pivot index 5
Post swap data [1 9 1 7 1 0 5 1 9 9]
Current data [1 9 1 7 1 0 5 1 9 9]
Pivot=1	Item=1
Current ind

array([1, 9, 1, 7, 1, 0, 5, 1, 9, 9])

In [291]:
# Quicksort algorithm
def quicksort(array, low = None, high = None):
    if low < high:
        sub = partition(array, low, high)
        quicksort(sub, low, len(sub))
        quicksort(sub, len(sub), high)


def partition(array, low = None, high = None):
    ''' Partition array based on the last item in the array '''
    pivot = array[high]
    print(pivot)
    print(array)
    for i, item in enumerate(array):
        if item > pivot:
            swap(array, low, high)
        print(array)
        print(item, pivot, item > pivot)
        
    
def swap(array, low, high):
    current = array[low]
    while high > 0:
        array[low] = array[low + 1]
        high -= 1
    array[high] = current

In [292]:
array = np.random.randint(0, 10, size=10)
print(array)
partition(array, 0, 9)

[9 5 6 5 4 2 6 1 6 7]
7
[9 5 6 5 4 2 6 1 6 7]
[9 5 6 5 4 2 6 1 6 7]
9 7 True
[9 5 6 5 4 2 6 1 6 7]
5 7 False
[9 5 6 5 4 2 6 1 6 7]
6 7 False
[9 5 6 5 4 2 6 1 6 7]
5 7 False
[9 5 6 5 4 2 6 1 6 7]
4 7 False
[9 5 6 5 4 2 6 1 6 7]
2 7 False
[9 5 6 5 4 2 6 1 6 7]
6 7 False
[9 5 6 5 4 2 6 1 6 7]
1 7 False
[9 5 6 5 4 2 6 1 6 7]
6 7 False
[9 5 6 5 4 2 6 1 6 7]
7 7 False


In [273]:
quicksort(array)

In partition [2 6 1 4 7 5 5 6 8 6] and len(array) 10
[] []
[2] []
[2, 6] []
[2, 6, 1] []
[2, 6, 1, 4] []
[2, 6, 1, 4] [7]
[2, 6, 1, 4, 5] [7]
[2, 6, 1, 4, 5, 5] [7]
[2, 6, 1, 4, 5, 5, 6] [7]
[2, 6, 1, 4, 5, 5, 6] [7, 8]
In partition [2, 6, 1, 4, 5, 5, 6, 6] and len(array) 8
[] []
[2] []
[2, 6] []
[2, 6, 1] []
[2, 6, 1, 4] []
[2, 6, 1, 4, 5] []
[2, 6, 1, 4, 5, 5] []
[2, 6, 1, 4, 5, 5, 6] []
In partition [2, 6, 1, 4, 5, 5, 6, 6] and len(array) 8
[] []
[2] []
[2, 6] []
[2, 6, 1] []
[2, 6, 1, 4] []
[2, 6, 1, 4, 5] []
[2, 6, 1, 4, 5, 5] []
[2, 6, 1, 4, 5, 5, 6] []
In partition [2, 6, 1, 4, 5, 5, 6, 6] and len(array) 8
[] []
[2] []
[2, 6] []
[2, 6, 1] []
[2, 6, 1, 4] []
[2, 6, 1, 4, 5] []
[2, 6, 1, 4, 5, 5] []
[2, 6, 1, 4, 5, 5, 6] []
In partition [2, 6, 1, 4, 5, 5, 6, 6] and len(array) 8
[] []
[2] []
[2, 6] []
[2, 6, 1] []
[2, 6, 1, 4] []
[2, 6, 1, 4, 5] []
[2, 6, 1, 4, 5, 5] []
[2, 6, 1, 4, 5, 5, 6] []
In partition [2, 6, 1, 4, 5, 5, 6, 6] and len(array) 8
[] []
[2] []
[2, 6] []
[2, 6, 1] 

KeyboardInterrupt: 